import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createServer } from "node:http";
import { chmod, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { HarborRuntime } from "./index.js";

const binary = process.env.HARBOR_OBSCURA_PATH;

test("Obscura runs through managed Profile, Instance, snapshot, input and restart persistence", { skip: !binary }, async () => {
  const root = await mkdtemp(join(tmpdir(), "harbor-obscura-live-"));
  const server = createServer((request, response) => {
    response.setHeader("content-type", "text/html; charset=utf-8");
    if (request.url === "/first") response.setHeader("set-cookie", "sid=alpha; Path=/; HttpOnly; SameSite=Lax");
    const persisted = request.headers.cookie?.includes("sid=alpha") ?? false;
    response.end(`<!doctype html><meta charset=utf-8><title>${persisted ? "Persisted" : "Fresh"}</title><body style="min-height:3000px"><h1>受控记录</h1><div style="height:180px"></div><input aria-label="内容" style="position:absolute;left:20px;top:70px;width:300px;z-index:10"><input aria-label="延迟替换" style="position:absolute;left:20px;top:120px;width:300px"><button aria-label="安排替换" style="position:absolute;left:350px;top:70px;width:120px" onclick="setTimeout(()=>{const old=document.querySelector('[aria-label=延迟替换]'),next=old.nextSibling;old.remove();const el=document.createElement('input');el.setAttribute('aria-label','延迟替换');el.style.cssText='position:absolute;left:20px;top:120px;width:300px';document.body.insertBefore(el,next)},50)">安排替换</button><button aria-label="覆盖输入框" style="position:absolute;left:350px;top:120px;width:120px" onclick="{const el=document.createElement('div');el.style.cssText='position:absolute;left:20px;top:120px;width:304px;height:30px;z-index:20;background:white';document.body.append(el)}">覆盖输入框</button><input aria-label="普通字段" value="correct-horse-battery-staple"><button onclick="localStorage.setItem('note',document.querySelector('[aria-label=内容]').value);document.querySelector('#draft').textContent='草稿：'+document.querySelector('[aria-label=内容]').value;this.textContent='已保存'">保存</button><button aria-label="清除状态" onclick="localStorage.removeItem('note');document.querySelector('[aria-label=内容]').value='';document.querySelector('#draft').textContent='草稿：空'">清除状态</button><p id="draft">草稿：空</p><p id="locale"></p><p>eyJhbGciOiJIUzI1NiJ9.payload.signature</p><p>${request.headers.cookie ?? "missing"}</p><script>const content=document.querySelector('[aria-label=内容]');content.value=localStorage.getItem('note')||'';document.title+='|'+(localStorage.getItem('note')||'missing');document.querySelector('#locale').textContent='语言：'+navigator.language;const save=()=>{localStorage.setItem('note',content.value);document.querySelector('#draft').textContent='草稿：'+content.value};document.querySelector('#draft').textContent='草稿：'+(content.value||'空');content.addEventListener('input',save);content.addEventListener('keydown',event=>{if(event.key==='Enter')save()});</script></body>`);
  });
  await new Promise<void>((resolve, reject) => server.once("error", reject).listen(0, "127.0.0.1", resolve));
  const address = server.address();
  const origin = `http://127.0.0.1:${typeof address === "object" && address ? address.port : 0}`;
  const previousRoot = process.env.HARBOR_PROFILE_STORAGE_ROOT;
  const previousPrivate = process.env.HARBOR_OBSCURA_ALLOW_PRIVATE_NETWORK;
  process.env.HARBOR_PROFILE_STORAGE_ROOT = root;
  process.env.HARBOR_OBSCURA_ALLOW_PRIVATE_NETWORK = "1";
  const runtime = new HarborRuntime();
  try {
    const created = runtime.mutateLocalIdentityEnvironment({ operation: "create", idempotency_key: "obscura-live-create", identity_environment: { requested_provider_id: "obscura", language: "en-US", site: { site_id: "controlled", origin, display_name: "Controlled" } } });
    assert.equal(created.status, "completed");
    const identityRef = created.identity_environment_ref!;
    const opened = await runtime.openManagedIdentityEnvironmentSession({ identity_environment_ref: identityRef, operation_scope: "profile_management", url: `${origin}/first`, control_owner: "core_task", holder_ref: "run_obscura_live", headless: true });
    assert.equal("status" in opened, false);
    if ("status" in opened) throw new Error(opened.message);
    assert.equal(opened.facts.some(fact => fact.key === "provider.id" && fact.value === "obscura"), true);
    assert.equal(opened.availability.driver, "available");
    assert.equal(opened.availability.viewer, "available");

    const watched = await runtime.captureViewerFrame(opened.runtime_session_ref, opened.viewer_ref!);
    assert.equal("status" in watched, false);
    if ("status" in watched) throw new Error(watched.failure_class);
    assert.equal(watched.mime_type, "image/png");
    assert.ok(watched.byte_length > 0);
    assert.equal(watched.privacy_boundary.retention, "not_retained");

    const handoff = runtime.recordHandoff(opened.runtime_session_ref, { control_owner: "user", handoff_reason: "user_requested" });
    assert.equal("status" in handoff, false);
    const controlled = await runtime.captureViewerFrame(opened.runtime_session_ref, opened.viewer_ref!);
    if ("status" in controlled) throw new Error(controlled.failure_class);
    const humanInput = await runtime.operateViewerInput(opened.runtime_session_ref, { viewer_ref: opened.viewer_ref!, frame_ref: controlled.frame_ref, operation_ref: "viewer_input_obscura_human", action: "input", x: 100, y: 85, text: "人工中文" });
    assert.equal(humanInput.status, "completed", JSON.stringify(humanInput));
    assert.equal((await runtime.operateViewerInput(opened.runtime_session_ref, { viewer_ref: opened.viewer_ref!, frame_ref: controlled.frame_ref, operation_ref: "viewer_input_obscura_human", action: "input", x: 100, y: 85, text: "人工中文" })).status, "completed");
    const humanCommit = await runtime.operateViewerInput(opened.runtime_session_ref, { viewer_ref: opened.viewer_ref!, frame_ref: humanInput.frame.frame_ref, operation_ref: "viewer_input_obscura_human_commit", action: "press", key: "Enter" });
    assert.equal(humanCommit.status, "completed");
    const scheduledFrame = await runtime.operateViewerInput(opened.runtime_session_ref, { viewer_ref: opened.viewer_ref!, frame_ref: humanCommit.frame.frame_ref, operation_ref: "viewer_input_obscura_schedule", action: "click", x: 400, y: 85 });
    assert.equal(scheduledFrame.status, "completed");
    await new Promise(resolve => setTimeout(resolve, 100));
    const staleViewer = await runtime.operateViewerInput(opened.runtime_session_ref, { viewer_ref: opened.viewer_ref!, frame_ref: scheduledFrame.frame.frame_ref, operation_ref: "viewer_input_obscura_stale", action: "input", x: 100, y: 135, text: "不得派发" });
    if (staleViewer.status === "completed") throw new Error("stale Viewer frame unexpectedly dispatched");
    assert.equal(staleViewer.failure_class, "viewer_frame_stale");
    const freshFrame = await runtime.captureViewerFrame(opened.runtime_session_ref, opened.viewer_ref!);
    if ("status" in freshFrame) throw new Error(freshFrame.failure_class);
    const coveredFrame = await runtime.operateViewerInput(opened.runtime_session_ref, { viewer_ref: opened.viewer_ref!, frame_ref: freshFrame.frame_ref, operation_ref: "viewer_input_obscura_cover", action: "click", x: 400, y: 135 });
    assert.equal(coveredFrame.status, "completed");
    const coveredInput = await runtime.operateViewerInput(opened.runtime_session_ref, { viewer_ref: opened.viewer_ref!, frame_ref: coveredFrame.frame.frame_ref, operation_ref: "viewer_input_obscura_covered", action: "input", x: 100, y: 135, text: "不得穿透" });
    if (coveredInput.status === "completed") throw new Error("covered Viewer target unexpectedly received input");
    assert.equal(coveredInput.failure_class, "viewer_input_target_unavailable");
    const blockedAgent = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "snapshot", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_blocked_during_human" });
    assert.equal(blockedAgent.failure_class, "control_lock_conflict");
    assert.equal("status" in runtime.releaseSession(opened.runtime_session_ref, { control_owner: "user" }), false);
    assert.equal("status" in runtime.lockSession(opened.runtime_session_ref, { control_owner: "core_task", holder_ref: "run_obscura_live" }), false);

    let snapshot = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "snapshot", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_snapshot" });
    assert.equal(snapshot.status, "completed", JSON.stringify(snapshot));
    assert.equal(JSON.stringify(snapshot).includes("correct-horse-battery-staple"), false);
    assert.equal(JSON.stringify(snapshot).includes("sid=alpha"), false);
    assert.equal(JSON.stringify(snapshot).includes("eyJhbGciOiJIUzI1NiJ9"), false);
    assert.match(snapshot.snapshot?.text ?? "", /草稿：人工中文/);
    assert.match(snapshot.snapshot?.text ?? "", /语言：en-US/);
    const schedule = snapshot.snapshot?.controls.find(control => control.name === "安排替换");
    const delayed = snapshot.snapshot?.controls.find(control => control.name === "延迟替换");
    assert.ok(schedule && delayed);
    const scheduled = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "click", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_schedule_replace", page_ref: snapshot.snapshot!.page_ref, observation_ref: snapshot.snapshot!.observation_ref, target_ref: schedule.target_ref });
    assert.equal(scheduled.status, "completed");
    await new Promise(resolve => setTimeout(resolve, 100));
    const stale = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "input", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_stale_target", page_ref: scheduled.snapshot!.page_ref, observation_ref: scheduled.snapshot!.observation_ref, target_ref: scheduled.snapshot!.controls.find(control => control.name === "延迟替换")!.target_ref, text: "不得派发" });
    assert.equal(stale.status, "unavailable");
    assert.equal(stale.dispatch_state, "not_dispatched");
    assert.equal(stale.failure_class, "managed_interaction_stale_target");
    snapshot = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "snapshot", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_snapshot_after_replace" });
    assert.equal(snapshot.status, "completed");
    const textbox = snapshot.snapshot?.controls.find(control => control.role === "textbox");
    assert.ok(textbox);
    const input = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "input", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_input", page_ref: snapshot.snapshot!.page_ref, observation_ref: snapshot.snapshot!.observation_ref, target_ref: textbox!.target_ref, text: "中文验证" });
    assert.equal(input.status, "completed");
    assert.equal(input.snapshot?.controls.find(control => control.role === "textbox")?.value, undefined);
    const button = input.snapshot?.controls.find(control => control.name === "保存");
    assert.ok(button);
    const clicked = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "click", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_click", page_ref: input.snapshot!.page_ref, observation_ref: input.snapshot!.observation_ref, target_ref: button!.target_ref });
    assert.equal(clicked.status, "completed");
    assert.equal(clicked.snapshot?.controls.some(control => control.name === "已保存"), true);
    const scrolled = await runtime.operateManagedInteraction(opened.runtime_session_ref, { action: "scroll", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_live", operation_ref: "operation_obscura_scroll", page_ref: clicked.snapshot!.page_ref, observation_ref: clicked.snapshot!.observation_ref, delta_y: 300 });
    assert.equal(scrolled.status, "completed");
    const captured = await runtime.captureLiveSnapshot(opened.runtime_session_ref);
    assert.equal(captured.status, "captured");
    await runtime.stopSession(opened.runtime_session_ref, { control_owner: "core_task", holder_ref: "run_obscura_live" });

    const reopened = await runtime.openManagedIdentityEnvironmentSession({ identity_environment_ref: identityRef, operation_scope: "profile_management", url: `${origin}/echo`, control_owner: "core_task", holder_ref: "run_obscura_reopen", headless: true });
    assert.equal("status" in reopened, false);
    if ("status" in reopened) throw new Error(reopened.message);
    assert.equal(reopened.current_page.title, "Persisted|人工中文中文验证");
    const persisted = await runtime.operateManagedInteraction(reopened.runtime_session_ref, { action: "snapshot", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_reopen", operation_ref: "operation_obscura_persisted" });
    assert.equal(persisted.status, "completed");
    assert.equal(JSON.stringify(persisted).includes("sid=alpha"), false);
    assert.match(persisted.snapshot?.text ?? "", /草稿：人工中文中文验证/);

    const [profileDirectory] = await readdir(root);
    assert.ok(profileDirectory);
    const profilePath = join(root, profileDirectory);
    const storagePath = join(profilePath, "obscura-local-storage-v1.json");
    const storageBeforeFailure = await readFile(storagePath);
    await chmod(profilePath, 0o500);
    const failedWrite = await runtime.operateManagedInteraction(reopened.runtime_session_ref, { action: "input", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_reopen", operation_ref: "operation_obscura_storage_write_failure", page_ref: persisted.snapshot!.page_ref, observation_ref: persisted.snapshot!.observation_ref, target_ref: persisted.snapshot!.controls.find(control => control.role === "textbox")!.target_ref, text: "写盘失败不覆盖" });
    assert.equal(failedWrite.status, "unknown_outcome");
    await chmod(profilePath, 0o700);
    assert.deepEqual(await readFile(storagePath), storageBeforeFailure);
    const afterFailedWrite = await runtime.operateManagedInteraction(reopened.runtime_session_ref, { action: "snapshot", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_reopen", operation_ref: "operation_obscura_after_storage_write_failure" });
    assert.equal(afterFailedWrite.status, "completed");
    const clear = afterFailedWrite.snapshot?.controls.find(control => control.name === "清除状态");
    assert.ok(clear);
    const cleared = await runtime.operateManagedInteraction(reopened.runtime_session_ref, { action: "click", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_reopen", operation_ref: "operation_obscura_clear_storage", page_ref: afterFailedWrite.snapshot!.page_ref, observation_ref: afterFailedWrite.snapshot!.observation_ref, target_ref: clear!.target_ref });
    assert.equal(cleared.status, "completed");
    await runtime.stopSession(reopened.runtime_session_ref, { control_owner: "core_task", holder_ref: "run_obscura_reopen" });

    const reopenedAfterDelete = await runtime.openManagedIdentityEnvironmentSession({ identity_environment_ref: identityRef, operation_scope: "profile_management", url: `${origin}/echo`, control_owner: "core_task", holder_ref: "run_obscura_delete_readback", headless: true });
    if ("status" in reopenedAfterDelete) throw new Error(reopenedAfterDelete.message);
    assert.equal(reopenedAfterDelete.current_page.title, "Persisted|missing");
    const providerPids = execFileSync("/bin/ps", ["-axo", "pid=,command="], { encoding: "utf8" }).split("\n")
      .filter(line => line.includes("obscura serve") && line.includes(root)).map(line => Number(line.trim().split(/\s+/, 1)[0])).filter(Number.isSafeInteger);
    assert.equal(providerPids.length, 1);
    process.kill(providerPids[0]!, "SIGKILL");
    const deadline = Date.now() + 2000;
    while (runtime.getSession(reopenedAfterDelete.runtime_session_ref)?.lifecycle_state !== "disconnected" && Date.now() < deadline) await new Promise(resolve => setTimeout(resolve, 10));
    assert.equal(runtime.getSession(reopenedAfterDelete.runtime_session_ref)?.lifecycle_state, "disconnected");
    assert.equal(runtime.getSession(reopenedAfterDelete.runtime_session_ref)?.control_owner, "none");
    assert.equal((await runtime.captureLiveSnapshot(reopenedAfterDelete.runtime_session_ref)).status, "unavailable");
    await runtime.stopSession(reopenedAfterDelete.runtime_session_ref);
    const boundedOrigins = Array.from({ length: 64 }, (_, index) => ({ origin: `https://site-${index}.example`, entries: [] }));
    await writeFile(storagePath, JSON.stringify({ schema_version: "harbor-obscura-local-storage/v1", origins: boundedOrigins }));
    const originLimited = await runtime.openManagedIdentityEnvironmentSession({ identity_environment_ref: identityRef, operation_scope: "profile_management", url: `${origin}/echo`, control_owner: "core_task", holder_ref: "run_obscura_origin_limit", headless: true });
    if ("status" in originLimited) throw new Error(originLimited.message);
    const originLimitSnapshot = await runtime.operateManagedInteraction(originLimited.runtime_session_ref, { action: "snapshot", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_origin_limit", operation_ref: "operation_obscura_origin_limit_snapshot" });
    if (originLimitSnapshot.status !== "completed" || !originLimitSnapshot.snapshot) throw new Error("origin-limit snapshot unavailable");
    const originLimitInput = await runtime.operateManagedInteraction(originLimited.runtime_session_ref, { action: "input", expected_origin: origin, controlled_origin: origin, holder_ref: "run_obscura_origin_limit", operation_ref: "operation_obscura_origin_limit_input", page_ref: originLimitSnapshot.snapshot!.page_ref, observation_ref: originLimitSnapshot.snapshot!.observation_ref, target_ref: originLimitSnapshot.snapshot!.controls.find(control => control.role === "textbox")!.target_ref, text: "第六十五来源" });
    assert.equal(originLimitInput.status, "completed");
    assert.equal(JSON.parse(await readFile(storagePath, "utf8")).origins.length, 65);
    await runtime.stopSession(originLimited.runtime_session_ref, { control_owner: "core_task", holder_ref: "run_obscura_origin_limit" });
    await writeFile(storagePath, '{"schema_version":"unknown","origins":[]}');
    const corrupt = await runtime.openManagedIdentityEnvironmentSession({ identity_environment_ref: identityRef, operation_scope: "profile_management", url: `${origin}/echo`, control_owner: "core_task", holder_ref: "run_obscura_corrupt", headless: true });
    assert.equal("status" in corrupt, false);
    if (!("status" in corrupt)) assert.equal(corrupt.availability.driver, "unavailable");
    assert.equal(await readFile(storagePath, "utf8"), '{"schema_version":"unknown","origins":[]}');
  } finally {
    await runtime.close();
    await new Promise<void>(resolve => server.close(() => resolve()));
    if (previousRoot === undefined) delete process.env.HARBOR_PROFILE_STORAGE_ROOT; else process.env.HARBOR_PROFILE_STORAGE_ROOT = previousRoot;
    if (previousPrivate === undefined) delete process.env.HARBOR_OBSCURA_ALLOW_PRIVATE_NETWORK; else process.env.HARBOR_OBSCURA_ALLOW_PRIVATE_NETWORK = previousPrivate;
    await rm(root, { recursive: true, force: true });
  }
});
