import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createFileManagedAccessStore, ManagedAccessError, type ManagedAccessRequest, type ManagedCreationTemplate } from "./managed-access.js";

const directory = await mkdtemp(join(tmpdir(), "managed-access-check-"));
try {
  const store = createFileManagedAccessStore({ directory });
  const reloaded = createFileManagedAccessStore({ directory });
  const digest = createHash("sha256").update("test-only-credential").digest("hex");
  const principalInput = { idempotency_key: "principal", display_name: "host", credential_hash: digest };
  const principal = await store.registerPrincipal(principalInput);
  assert.deepEqual(await store.registerPrincipal({ credential_hash: digest, display_name: "host", idempotency_key: "principal" }), principal);
  const rejected = async (action: Promise<unknown>, code: string) => assert.rejects(action, (error: unknown) => error instanceof ManagedAccessError && error.code === code);
  await rejected(store.registerPrincipal({ ...principalInput, display_name: "changed" }), "managed_access_idempotency_conflict");
  await rejected(store.authenticateCredential("0".repeat(64)), "managed_access_authentication_required");
  const connection = await store.connect(digest);
  const template: ManagedCreationTemplate = { template_ref: "template:camoufox", provider_id: "camoufox", site: { site_id: "example", origin: "https://example.com", display_name: "Example" }, language: "en-US", timezone: "UTC", permission_ceiling: { allowed_operations: ["profile.list", "profile.read", "instance.start", "instance.observe"], allowed_origins: ["https://example.com"] } };
  const grant = await store.createGrant({ idempotency_key: "grant", principal_id: principal.principal_id, profile_refs: [], allowed_operations: ["profile.create", ...template.permission_ceiling.allowed_operations, "instance.stop"], allowed_origins: ["https://example.com"], expires_at: new Date(Date.now() + 60_000).toISOString(), creation_template: template, max_created_profiles: 2 });
  const request: ManagedAccessRequest = { connection_id: connection.connection_id, grant_id: grant.grant_id, operation: "profile.create", template_ref: template.template_ref, task_scope: { operations: ["profile.create"], profile_refs: [], origins: ["https://example.com"] } };
  assert.deepEqual((await store.checkAccess(digest, request)).creation_template, template);
  await rejected(store.checkAccess(digest, { ...request, template_ref: "template:wider" }), "managed_access_creation_denied");
  await rejected(store.checkAccess(digest, { ...request, permission_ceiling: { allowed_operations: ["instance.stop"] } }), "managed_access_invalid_input");
  await rejected(store.checkAccess(digest, { ...request, connection_id: "connection:forged" }), "managed_access_connection_unavailable");
  await store.recordCreatedProfile({ idempotency_key: "created-a", grant_id: grant.grant_id, profile_ref: "profile:a" });
  await store.recordCreatedProfile({ idempotency_key: "created-b", grant_id: grant.grant_id, profile_ref: "profile:b" });
  await store.recordCreatedProfile({ idempotency_key: "created-a", grant_id: grant.grant_id, profile_ref: "profile:a" });
  await rejected(store.recordCreatedProfile({ idempotency_key: "created-c", grant_id: grant.grant_id, profile_ref: "profile:c" }), "managed_access_creation_denied");
  const access: ManagedAccessRequest = { connection_id: connection.connection_id, grant_id: grant.grant_id, operation: "instance.start", profile_ref: "profile:a", origin: "https://example.com", task_scope: { operations: ["instance.start", "instance.stop"], profile_refs: ["profile:a", "profile:b"], origins: ["https://example.com"] } };
  assert.equal((await reloaded.checkAccess(digest, access)).profile_policy?.profile_ref, "profile:a");
  await rejected(store.checkAccess(digest, { ...access, operation: "instance.stop" }), "managed_access_denied");
  await rejected(store.checkAccess(digest, { ...access, origin: "https://other.example" }), "managed_access_denied");
  await rejected(store.checkAccess(digest, { ...access, task_scope: { ...access.task_scope, profile_refs: ["profile:b"] } }), "managed_access_denied");
  await store.setProfilePolicy({ idempotency_key: "restrict-a", profile_ref: "profile:a", allowed_operations: [], allowed_origins: [] });
  await rejected(reloaded.checkAccess(digest, access), "managed_access_denied");
  assert.equal((await reloaded.checkAccess(digest, { ...access, profile_ref: "profile:b" })).profile_policy?.profile_ref, "profile:b");
  const otherDigest = createHash("sha256").update("other-test-credential").digest("hex");
  await store.registerPrincipal({ idempotency_key: "other-principal", display_name: "other", credential_hash: otherDigest });
  const otherConnection = await store.connect(otherDigest);
  await rejected(store.checkAccess(otherDigest, { ...access, connection_id: otherConnection.connection_id }), "managed_access_denied");
  const quotaGrant = await store.createGrant({ idempotency_key: "quota-grant", principal_id: principal.principal_id, profile_refs: [], allowed_operations: ["profile.create"], allowed_origins: ["https://example.com"], expires_at: new Date(Date.now() + 60_000).toISOString(), creation_template: template, max_created_profiles: 1 });
  const concurrent = await Promise.allSettled(["c", "d"].map(id => reloaded.recordCreatedProfile({ idempotency_key: `quota-${id}`, grant_id: quotaGrant.grant_id, profile_ref: `profile:${id}` })));
  assert.equal(concurrent.filter(item => item.status === "fulfilled").length, 1);
  assert.equal(concurrent.filter(item => item.status === "rejected" && item.reason.code === "managed_access_creation_denied").length, 1);
  await store.revokeGrant({ idempotency_key: "revoke", grant_id: grant.grant_id });
  const reconnect = await reloaded.connect(digest);
  await rejected(reloaded.checkAccess(digest, { ...access, connection_id: reconnect.connection_id, profile_ref: "profile:b" }), "managed_access_grant_unavailable");
  await store.revokeConnection({ idempotency_key: "disconnect", connection_id: reconnect.connection_id });
  await rejected(reloaded.checkAccess(digest, { ...access, connection_id: reconnect.connection_id }), "managed_access_connection_unavailable");
  assert.equal(JSON.stringify(await store.list()).includes(digest), false);
  assert.equal((await readFile(join(directory, "managed-access.json"), "utf8")).includes("test-only-credential"), false);
  await store.revokePrincipal({ idempotency_key: "remove-host", principal_id: principal.principal_id });
  await rejected(reloaded.connect(digest), "managed_access_authentication_required");
  console.log("managed access self-check passed");
} finally { await rm(directory, { recursive: true, force: true }); }
