import type { TaskProjection } from "./taskThreadFixtures";

export const realWritePreviewTaskFixtures: TaskProjection[] = [
  {
    id: "task-xhs-publish-write-preview",
    title: "小红书发布草稿写前验证",
    accountIdentity: "小红书运营号 A",
    siteSkill: "小红书发布草稿写前预览",
    businessInput: "笔记标题：AI 工具清单；草稿来源：素材包 2026-07-06",
    source: "Core fixture",
    packageSource: {
      name: "@lode/xiaohongshu-write-pre-preview",
      version: "0.1.0",
      capabilityRef: "lode://capability/xiaohongshu/publish-draft-write-preview",
      sourceRef: "lode://package/xiaohongshu-write-pre-preview@0.1.0",
      lockRef: "lode://lock/xiaohongshu-write-pre-preview/2026-07-06",
      fetchedAt: "2026-07-06T10:18:00Z",
      source: "Lode fixture",
      boundary: "App 只展示小红书真实页面写前验证 projection；不点击发布、不进入 Stage 7、不保存 raw evidence。",
    },
    runs: [
      {
        id: "run-xhs-write-preview-ready",
        label: "小红书 Preview 006",
        lifecycle: "needs-action",
        outcome: "partial",
        summary: "真实页面写前验证已生成：标题、正文和话题将写入小红书发布草稿；submitted=false / 未提交，当前未发布。",
        actionIntent: "Owner-supported action intent: 审批请求仅用于后续受控阶段；本 App 表面只能记录取消意图或刷新验证。",
        owner: "Core",
        source: "Core fixture",
        resultRows: [
          { label: "Result kind", value: "real_page_write_precheck_projection", source: "Core fixture" },
          { label: "Submitted", value: "false / 未提交", source: "Core fixture" },
          { label: "发布状态", value: "未发布", source: "Core fixture" },
          { label: "目标页面", value: "小红书发布器草稿页", source: "Harbor fixture" },
        ],
        fieldSources: [
          {
            field: "标题输入框",
            value: "AI 工具清单：运营提效的 7 个场景",
            locator: "page-ref:xhs-publish-composer / element-ref:title-input",
            evidenceRef: "screenshot://harbor/xhs-preview-006/title-input",
            source: "Harbor fixture",
          },
          {
            field: "正文编辑区",
            value: "包含开头、分点正文和结尾行动提示",
            locator: "page-ref:xhs-publish-composer / element-ref:body-editor",
            evidenceRef: "evidence://core/xhs-preview-006/body-change",
            source: "Core fixture",
          },
          {
            field: "话题标签",
            value: "#AI工具 #运营效率",
            locator: "page-ref:xhs-publish-composer / element-ref:topic-token-list",
            evidenceRef: "evidence://core/xhs-preview-006/topic-tags",
            source: "Core fixture",
          },
        ],
        evidenceCards: [
          {
            id: "ev-xhs-write-preview-before",
            title: "小红书发布器写前证据",
            summary: "Harbor 只提供发布器截图 ref、字段 ref 和 freshness；App 不保存截图正文、DOM、Cookie 或 profile storage。",
            viewerLabel: "打开小红书写前证据",
            viewerHref: "#evidence-viewer-xhs-write-preview-006",
            source: "Harbor fixture",
            status: "available",
            freshness: "fresh",
            provenance: "Core action request + Harbor composer refs + Lode expected_change",
          },
        ],
        capabilityAttribution: {
          capabilityRef: "lode://capability/xiaohongshu/publish-draft-write-preview",
          version: "0.1.0",
          sourceRef: "lode://package/xiaohongshu-write-pre-preview@0.1.0",
          failureClass: "none",
          summary: "小红书写前验证绑定 Lode expected_change、Core action request 和 Harbor 发布器 ref。",
        },
        writePrecheck: {
          state: "available",
          modeLabel: "真实页面写前验证 / draft-only",
          expectedChangeSummary: "预期变化：在小红书发布草稿页填入标题、正文、图片占位和话题；不会点击发布。",
          beforeLabel: "草稿页为空，发布按钮未触发",
          afterLabel: "仅投影待填内容，发布状态仍为未发布",
          diffRows: [
            {
              label: "标题",
              before: "空",
              after: "AI 工具清单：运营提效的 7 个场景",
              source: "Lode fixture",
            },
            {
              label: "正文",
              before: "空",
              after: "本周测试的工具清单、适用场景和注意事项",
              source: "Lode fixture",
            },
            {
              label: "发布按钮",
              before: "未点击",
              after: "未点击 / submitted=false",
              source: "Core fixture",
            },
          ],
          noSubmitGuard: "active",
          stateNote: "未发布：这只是小红书真实页面写前验证投影，submitted=false / 未提交。",
        },
        approval: {
          actionRequestId: "action-request:fixture/xhs-publish-draft-preview-006",
          riskLabel: "write-pre / medium / no-submit",
          riskLevel: "low",
          statuses: [
            {
              label: "审批请求",
              status: "pending",
              detail: "等待用户审查预期变化；当前只允许取消或刷新验证。",
            },
            {
              label: "过期请求",
              status: "expired",
              detail: "页面 ref 过期后不能继续审批，也不能显示为成功。",
            },
            {
              label: "取消记录",
              status: "cancelled",
              detail: "取消只关闭写前验证，不产生发布结果。",
            },
          ],
          cancelIntent: "记录取消意图；不发送发布动作。",
          boundary: "Core 拥有 action request 和 submitted=false truth；App 不执行 approval execution。",
        },
        process: [
          "Core returned write-pre action request with submitted=false.",
          "Lode supplied expected_change for the Xiaohongshu publish draft.",
          "Harbor supplied fresh composer refs without raw evidence body.",
        ],
      },
      {
        id: "run-xhs-write-preview-expired",
        label: "小红书 Preview 005",
        lifecycle: "blocked",
        outcome: "expired",
        summary: "页面状态已过期，写前验证不能继续；App 显示过期而不是成功，submitted=false / 未提交。",
        actionIntent: "Owner-supported action intent: 刷新小红书发布器页面后重新生成写前验证。",
        owner: "Core",
        source: "Core fixture",
        resultRows: [
          { label: "Preview state", value: "expired", source: "Core fixture" },
          { label: "Submitted", value: "false / 未提交", source: "Core fixture" },
          { label: "发布状态", value: "未发布", source: "Core fixture" },
        ],
        evidenceCards: [
          {
            id: "ev-xhs-write-preview-expired",
            title: "小红书写前验证过期证据",
            summary: "Harbor freshness 标记页面 ref 过期；App 不复用旧截图，也不推断提交成功。",
            viewerLabel: "打开过期证据",
            viewerHref: "#evidence-viewer-xhs-write-preview-expired",
            source: "Harbor fixture",
            status: "expired",
            freshness: "expired",
            provenance: "Harbor composer ref freshness",
          },
        ],
        capabilityAttribution: {
          capabilityRef: "lode://capability/xiaohongshu/publish-draft-write-preview",
          version: "0.1.0",
          sourceRef: "lode://package/xiaohongshu-write-pre-preview@0.1.0",
          failureClass: "evidence_expired",
          summary: "过期是证据 freshness 问题；不能把写前验证显示成发布成功。",
        },
        writePrecheck: {
          state: "expired",
          modeLabel: "真实页面写前验证已过期",
          expectedChangeSummary: "预期变化被保留为历史记录，但不能审批或继续。",
          beforeLabel: "旧 RefMap",
          afterLabel: "无可用草稿投影",
          diffRows: [
            { label: "freshness", before: "fresh", after: "expired", source: "Harbor fixture" },
            { label: "submitted", before: "false", after: "false / 未提交", source: "Core fixture" },
          ],
          noSubmitGuard: "active",
          stateNote: "页面状态已过期；未发布，submitted=false / 未提交。",
        },
        process: ["Harbor marked composer refs expired.", "Core blocked approval request.", "App preserved no-submit state."],
      },
    ],
  },
  {
    id: "task-boss-greeting-write-preview",
    title: "BOSS 打招呼写前验证",
    accountIdentity: "BOSS 招聘号",
    siteSkill: "BOSS 打招呼写前预览",
    businessInput: "职位：高级前端工程师；候选人：最近活跃；消息模板：简短邀约",
    source: "Core fixture",
    packageSource: {
      name: "@lode/boss-greeting-write-pre-preview",
      version: "0.1.0",
      capabilityRef: "lode://capability/boss/greeting-write-preview",
      sourceRef: "lode://package/boss-greeting-write-pre-preview@0.1.0",
      lockRef: "lode://lock/boss-greeting-write-pre-preview/2026-07-06",
      fetchedAt: "2026-07-06T10:22:00Z",
      source: "Lode fixture",
      boundary: "App 只展示 BOSS 打招呼真实页面写前验证 projection；不点击发送、不投递、不保存聊天或简历材料。",
    },
    runs: [
      {
        id: "run-boss-greeting-preview-ready",
        label: "BOSS Preview 004",
        lifecycle: "needs-action",
        outcome: "partial",
        summary: "真实页面写前验证已生成：打招呼文案将进入候选人消息框；submitted=false / 未提交，当前未发送。",
        actionIntent: "Owner-supported action intent: 审查目标职位、候选人和文案；当前只能取消或重新验证。",
        owner: "Core",
        source: "Core fixture",
        resultRows: [
          { label: "Result kind", value: "real_page_write_precheck_projection", source: "Core fixture" },
          { label: "Submitted", value: "false / 未提交", source: "Core fixture" },
          { label: "发送状态", value: "未发送", source: "Core fixture" },
          { label: "目标职位", value: "高级前端工程师 · 上海某 SaaS 公司", source: "Core fixture" },
        ],
        fieldSources: [
          {
            field: "目标职位",
            value: "高级前端工程师 · 上海某 SaaS 公司",
            locator: "page-ref:boss-job-detail / element-ref:job-title",
            evidenceRef: "evidence://core/boss-greeting-preview-004/job",
            source: "Core fixture",
          },
          {
            field: "消息输入框",
            value: "你好，我正在为前端团队招募候选人，想和你简单沟通一下机会。",
            locator: "page-ref:boss-chat-drawer / element-ref:greeting-textarea",
            evidenceRef: "screenshot://harbor/boss-greeting-preview-004/message-box",
            source: "Harbor fixture",
          },
        ],
        evidenceCards: [
          {
            id: "ev-boss-greeting-preview",
            title: "BOSS 打招呼写前证据",
            summary: "证据只包含职位 ref、消息框 ref 和 viewer ref；App 不保存聊天材料、简历、DOM 或 network body。",
            viewerLabel: "打开 BOSS 打招呼写前证据",
            viewerHref: "#evidence-viewer-boss-greeting-preview-004",
            source: "Harbor fixture",
            status: "available",
            freshness: "fresh",
            provenance: "Core action request + Harbor chat drawer refs + Lode expected_change",
          },
        ],
        capabilityAttribution: {
          capabilityRef: "lode://capability/boss/greeting-write-preview",
          version: "0.1.0",
          sourceRef: "lode://package/boss-greeting-write-pre-preview@0.1.0",
          failureClass: "none",
          summary: "BOSS 写前验证绑定目标职位、候选人消息框 ref 和 no-submit guard。",
        },
        writePrecheck: {
          state: "available",
          modeLabel: "真实页面写前验证 / message draft",
          expectedChangeSummary: "预期变化：在 BOSS 候选人消息框填入打招呼文案；不会点击发送。",
          beforeLabel: "消息框为空，发送按钮未触发",
          afterLabel: "仅投影待发送文案，发送状态仍为未发送",
          diffRows: [
            {
              label: "目标职位",
              before: "职位详情页已打开",
              after: "高级前端工程师 · 上海某 SaaS 公司",
              source: "Core fixture",
            },
            {
              label: "打招呼文案",
              before: "空",
              after: "简短邀约文案",
              source: "Lode fixture",
            },
            {
              label: "发送按钮",
              before: "未点击",
              after: "未点击 / submitted=false",
              source: "Core fixture",
            },
          ],
          noSubmitGuard: "active",
          stateNote: "未发送：这只是 BOSS 真实页面写前验证投影，submitted=false / 未提交。",
        },
        approval: {
          actionRequestId: "action-request:fixture/boss-greeting-preview-004",
          riskLabel: "write-pre / medium / no-submit",
          riskLevel: "low",
          statuses: [
            {
              label: "审批请求",
              status: "pending",
              detail: "等待用户审查目标职位和打招呼文案。",
            },
            {
              label: "过期请求",
              status: "expired",
              detail: "候选人页 ref 过期后不能继续审批。",
            },
            {
              label: "取消记录",
              status: "cancelled",
              detail: "取消不会发送消息，也不会生成提交成功界面。",
            },
          ],
          cancelIntent: "记录取消意图；不发送打招呼消息。",
          boundary: "Core 拥有审批请求和 submitted=false truth；App 不执行真实发送。",
        },
        process: [
          "Core returned BOSS greeting action request with submitted=false.",
          "Lode supplied expected_change for the greeting message.",
          "Harbor supplied fresh job and message-box refs without raw chat material.",
        ],
      },
      {
        id: "run-boss-greeting-preview-cancelled",
        label: "BOSS Preview 003",
        lifecycle: "completed",
        outcome: "failure-safe",
        summary: "用户取消打招呼写前验证；消息未发送，submitted=false / 未提交。",
        actionIntent: "Owner-supported action intent: 重新生成写前验证或修改消息模板。",
        owner: "Core",
        source: "Core fixture",
        resultRows: [
          { label: "Preview state", value: "user_cancelled", source: "Core fixture" },
          { label: "Submitted", value: "false / 未提交", source: "Core fixture" },
          { label: "发送状态", value: "未发送", source: "Core fixture" },
        ],
        evidenceCards: [
          {
            id: "ev-boss-greeting-cancelled",
            title: "BOSS 取消写前验证证据",
            summary: "取消记录只链接 action request 和 owner refs；没有发送消息。",
            viewerLabel: "打开取消证据",
            viewerHref: "#evidence-viewer-boss-greeting-cancelled",
            source: "Core fixture",
            status: "available",
            freshness: "fresh",
            provenance: "Core cancellation query fixture",
          },
        ],
        capabilityAttribution: {
          capabilityRef: "lode://capability/boss/greeting-write-preview",
          version: "0.1.0",
          sourceRef: "lode://package/boss-greeting-write-pre-preview@0.1.0",
          failureClass: "none",
          summary: "取消是写前验证终止状态，不能显示为发送成功。",
        },
        writePrecheck: {
          state: "user_cancelled",
          modeLabel: "真实页面写前验证已取消",
          expectedChangeSummary: "预期变化已取消，不再请求审批或发送。",
          beforeLabel: "消息草稿等待审查",
          afterLabel: "取消后无待发送文案",
          diffRows: [
            { label: "approval", before: "pending", after: "cancelled", source: "Core fixture" },
            { label: "submitted", before: "false", after: "false / 未提交", source: "Core fixture" },
          ],
          noSubmitGuard: "active",
          stateNote: "已取消：BOSS 打招呼没有发送，submitted=false / 未提交。",
        },
        process: ["User cancellation recorded.", "Core kept no-submit guard active.", "App displays cancelled state as failure-safe history."],
      },
    ],
  },
];
